### ISSUE TITLE
Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:".

### ISSUE THREAD

**Issue by codewithanujith** [YassienW/react-bootstrap-editable#1]
React 16.9 throw warning about javascript URLs in a tags while using bootstrap editable. The support for the javascript URL will be removed in the next major version of react. The issue is in esitable.js file line 181. A quick fix will be much appreciated.

https://github.com/YassienW/react-bootstrap-editable/blob/448f5d3149dccc980a3fbd37bd1673ca77d4ee4e/src/Editable.js#L181

**Comment by YassienW** [comment]
Fixed in next release
