### ISSUE TITLE
prevent page reload when pressing "Enter"

### ISSUE THREAD

**Issue by nicokant** [YassienW/react-bootstrap-editable#2]
Hi, thanks for this library!
I've found a little problem while using it, when I edit a text if I press `Enter` I would expect the form containing the text field to be submitted without reloading the page.
Is there some configuration that could prevent this?

You can replicate this by visiting the storybook and just pressing `Enter` inside the text field while in editable mode.

**Comment by YassienW** [comment]
Released in 0.6.2 
Commit d0a3cd9b3d45429ea3c176f674708348cc7ec3c9
