### ISSUE TITLE
The ajax function passed to an Editable is called twice

### ISSUE THREAD

**Issue by jackslinger** [YassienW/react-bootstrap-editable#4]
### Expected behaviour

The ajax function provided to the Editable component should be called once if the validation was successful.

### Actual behaviour

The ajax function provided is called twice if the validation was successful.

### Steps to reproduce the behaviour

I have setup a storybook based on a fork of V0.8.0 located here: https://github.com/epigenesys/react-bootstrap-editable/tree/storybook

The last story features an Editable component with an ajax function that logs to the console. The following steps detail how to replicate the issue using this code.

1. Checkout the storybook located at https://github.com/epigenesys/react-bootstrap-editable/tree/storybook.
2. Run `yarn install`.
3. Run `yarn run storybook`.
4. Navigate to the 'Ajax' story.
5. Open the console in developer tools.
6. Change the value of the Editable and submit.
7. Observe that there are two console messages.

I have attempted to keep the code above as simple as possible to replicate the issue. Please let me know if you have any difficulty replicating the issue.

### Current theory as to the nature of the problem

The following is discussing the Editable.js file located here: https://github.com/YassienW/react-bootstrap-editable/blob/01b3fd899829100190956e1358989c5585307688/src/Editable.js

Both lines 108 and 207 add forms with the `onFormSubmit` function as their `onSubmit`. Adding console log statements to both of these lines show that they are both being called, which is then calling the `ajax` function twice. It looks like only one of these forms should have the `onSubmit` handler set to `onFormSubmit`.

**Comment by YassienW** [comment]
Fixed in 0.8.2
